### PR TITLE
First try…

### PR DESCRIPTION
**Pull request by lapineige**

### CODE REVIEW

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
Stuck forever in CI ??

**Comment by lapineige** [comment]
!testme

**Comment by Salamandar** [comment]
Looks like an interactive command that waits for interaction…

**Comment by OniriCorpe** [comment]
is it normal that it wants to install xorg and a bunch of GUI related stuff? 🥲

**Comment by lapineige** [comment]
!testme

**Comment by Salamandar** [comment]
> is it normal that it wants to install xorg and a bunch of GUI related stuff? 🥲

I'm pretty sure it's not… :'(
Also that will be garbage left in the system after the app is removed, because there's no dependency between the app and those packages :'(

**Comment by OniriCorpe** [comment]
Can we extract things from their docker, instead of this?

**Comment by lapineige** [comment]
Go for it 😅

**Comment by Salamandar** [comment]
Still stuck

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
Ok this is an insane use of apt by node, instead of managing things before the installation in a normal way…
So apparently it uses sudo to install things, and get the "first sudo use lecture" in CI.

I would vote for completely trashing that `install-deps` command that is doing way too much insure stuff for our use case.

**Comment by Lab-8916100448256** [comment]
(I don't know a lot of things about packaging apps for YUNoHost or with node.js. So bear with me if what I write is complete nonsense or if I ask stupid questions)

As to why this install-deps is installing an insane amount of things, including stuff that have nothing to do on a web app server, like xorg and web browsers : 
The install-deps command is part of framework used to automate web-app testing : the `playwright` module that is called with the install-deps parameter : https://playwright.dev/
It seems to me that the developers of linkwarden have left that into their docker image instead of figuring out the minimal part of its dependencies that is actually required to run the app without the test framework.
If that is the case, we could wait a long time before we get an answer to the question @lapineige asked in the issue he has created on linkwarden side.

I tried to comment out the step that calls `playwright install-deps`, but as expected I got an error about a missing dependency : `/bin/sh: 1: next: not found`

I could try adding `npm install next` to the install script in the fork of YunoHost-Apps/linkwarden_ynh I have made, then try to install again on my yunohost server and most likely get hit by another error because of a missing dependency, then find out what is missing and iterate until I have discovered all the missing dependencies.
But that will take a lot of time to go though the cycles of editing the install script in git and try to install linkwarden from scratch on my yunohost server.

Is there a way to leave the system as is when an error is happening during an app install? I mean not having yunohost automatically rollback everything. That way I could try finishing the install manually, which would be faster for me to discover all the missing dependencies.

**Comment by OniriCorpe** [comment]
> Is there a way to leave the system as is when an error is happening during an app install? I mean not having yunohost automatically rollback everything. That way I could try finishing the install manually, which would be faster for me to discover all the missing dependencies.

the setting you're looking for is:
`yunohost app install --no-remove-on-failure`

**Comment by Lab-8916100448256** [comment]
Thanks. 
It seems that adding `npm install next` was all that was needed to have the install complete successfully.
However the service fails on startup : 
```
Feb 13 02:17:22 vig-clic systemd[21921]: linkwarden.service: Failed at step EXEC spawning ynh_exec_as: No such file or directory
``` 
any idea how to fix this one?

**Comment by OniriCorpe** [comment]
maybe something like that?

```
User=__APP__
Group=__APP__
ExecStart=yarn start
```
https://github.com/YunoHost-Apps/linkwarden_ynh/blob/master/conf/systemd.service#L13

**Comment by Lab-8916100448256** [comment]
I had to tweak a bit these parts :  
> Environment="__NODE_ENV_PATH__"
> ExecStart=__YNH_NODE__ yarn start
And I now have the systemd service starting.

I still get a `502 Bad Gateway` though. It looks like this is coming from nginx doing a proxy_pass to port 39744 and having linkwarden listening on port 3000
So I guess I have to figure out how to change the default port 3000 used by linkwarden to the port allocated by yunohost

**Comment by OniriCorpe** [comment]
isn't this line supposed to do it?
https://github.com/YunoHost-Apps/linkwarden_ynh/blob/testing/conf/.env#L2

**Comment by Lab-8916100448256** [comment]
Wel, I do seem to have the correct port in the .env file : 
```
root@vig-clic ~ # grep NEXTAUTH_URL /var/www/linkwarden/.env
NEXTAUTH_URL=http://localhost:39744/api/v1/auth
```
But in the linkwarden log, it says it is listening on port 3000, like that poor guy that got slammed for having typed 2 words in upper case in the issue you mentioned  : 
```
root@vig-clic ~ # grep "started server" /var/log/linkwarden/linkwarden.log 
[0] - ready started server on 0.0.0.0:3000, url: http://localhost:3000
```

**Comment by Lab-8916100448256** [comment]
And if I try to change the port to 3000 on nginx side, I do have things working correctly, no more `502 Bad Gateway`

**Comment by OniriCorpe** [comment]
seems like an upstream issue :/

**Comment by Lab-8916100448256** [comment]
I'm not familiar enough with this node.js + React stuff, but it seems to me that NEXTAUTH_URL might not be what is configuring the port.
I'm going to try something along the line of what is described there : https://stackoverflow.com/questions/60245994/how-can-i-change-the-default-port-in-react-from-3000-to-another-port

**Comment by Lab-8916100448256** [comment]
Ah!
I tried manually adding a line with `PORT=39744` to the .env file and now I have this
```
root@vig-clic ~ # grep "started server" /var/log/linkwarden/linkwarden.log 
[0] - ready started server on 0.0.0.0:39744, url: http://localhost:39744
```
I'm going to integrate this in the yunohost install script and re-run the install from scratch to verify everything is good now

**Comment by Lab-8916100448256** [comment]
I confirm that installing from my fork is working correctly now. I don't have write acess to yunohost git, so I created a PR : https://github.com/YunoHost-Apps/linkwarden_ynh/pull/2

**Comment by Lab-8916100448256** [comment]
Thanks for your very usefull help @OniriCorpe

**Comment by OniriCorpe** [comment]
!testme

**Comment by lapineige** [comment]
> It seems to me that the developers of linkwarden have left that into their docker image instead of figuring out the minimal part of its dependencies that is actually required to run the app without the test framework.

Well that's a pitty…

**Comment by lapineige** [comment]
Thanks a lot to both of you for solving this :smiley:

**Comment by lapineige** [comment]
So the only stuff left is the subpath install, and the upgrade which fails with:
`24712 WARNING Variable $ynh_node_load_path wasn't initialized when trying to replace __YNH_NODE_LOAD_PATH__ in /etc/systemd/system/linkwarden.service`

**Comment by Tagadda** [comment]
yeah you have to call `ynh_use_nodejs` at least one line earlier to load thoses variables

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
` WARNING Variable $secret wasn't initialized when trying to replace __SECRET__ in /var/www/linkwarden/.env`

**Comment by OniriCorpe** [comment]
!testme

**Comment by OniriCorpe** [comment]
!testme

**Comment by OniriCorpe** [comment]
idk why the backup/restore test fails :/

**Comment by Lab-8916100448256** [comment]
The subdir install is passing the test, but it is not actually working yet. 
When I try to install on a yunohost server with all default values, for example on  `https://my-server.tld/linkwarden` I get error in my web browser console about scripts that are failing to load with URLs that are missing the subdir, for example : 
```
Loading failed for the <script> with source “https://myserver.tld/_next/static/chunks/framework-7a7e500878b44665.js”.
```

I tried some nginx url rewriting wizardry involving sub_filter and proxy_redirect spells to fix this but I haven't found the correct ones yet. I would need to study the [proxy_pass magic book](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass) some more to crack this one.

**Comment by lapineige** [comment]
> Or do we simply restrict the app to root install for now?

Yes, let's go for this, so we will have more testers.
Could you create an issue to document the need to work on the subpath ?

**Comment by Tagadda** [comment]
> idk why the backup/restore test fails :/

@OniriCorpe we miss the nodejs install in the restore script

**Comment by ericgaspar** [comment]
!testme

**Pull request merged**
